apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: django-heroku-template
  title: Django Heroku Template
  description: Create a simple template django with heroku as PaaS
  tags:
    - recommended
    - django
    - heroku
spec:
  owner: roblox@roblox.com
  templater: cookiecutter
  type: website
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Help others understand what this service does.
